name: Auto Release on Main Commit

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grants permission to create releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag and generate next version
        id: get_version
        run: |
          VERSION=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          if [[ -z "$VERSION" ]]; then
            VERSION="v1.0.0"
          else
            IFS='.' read -r -a parts <<< "${VERSION//v/}"
            PATCH=$((parts[2] + 1))
            VERSION="v${parts[0]}.${parts[1]}.$PATCH"
          fi
          echo "New version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create and push new version tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.version }}
          git push origin ${{ env.version }}

      - name: Create versioned release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.version }}
          name: Release ${{ env.version }}
          body: |
            Auto-generated release for commit: ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Update latest tag
        run: |
          git tag -fa latest -m "Latest release"
          git push origin latest --force
